=== rpmullig/DATABASES_AND_RELATED/XML/Projects_done_at_IU/Exercises/rpmullig_shcema1/rpmullig_AmazonInventory6.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"> 
    
    <xs:element name="INVENTORY">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="BOOK" type="bookType" minOccurs='0' maxOccurs='unbounded'/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    
    <xs:complexType name="bookType">
        <xs:sequence>
            <xs:element name="TITLE" type="xs:string"/>
            <xs:element name="SUBTITLE" type="xs:string" minOccurs='0' maxOccurs='unbounded'/>
            <xs:element name="AUTHOR" type="xs:string"/>
            <xs:element name="COAUTHOR" type="xs:string" minOccurs='0' maxOccurs='unbounded'/>
            <xs:element name="QUANTITY" type="xs:integer"/>
            <xs:element name="PRICE" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    
 <!--   <xs:simpleType name="priceType">
        <xs:restriction base="xs:decmial">
            <xs:pattern value="\d{1}.\d{2}"/>
            <xs:pattern value="\d{1}:\d{2}"/>
        </xs:restriction>
    </xs:simpleType>
    
    -->
</xs:schema>

=== rpmullig/DATABASES_AND_RELATED/XML/Projects_done_at_IU/Exercises/rpmullig_shcema1/AmazonInventory6.xml
<?xml version="1.0" encoding="UTF-8"?>

<INVENTORY xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="../Turnin/rpmullig_AmazonInventory6.xsd">
   <BOOK>
        <TITLE>Huckleberry Finn</TITLE>
        <SUBTITLE>Mark Twain Series</SUBTITLE>
	<AUTHOR>Mark Twain</AUTHOR>
        <COAUTHOR>none</COAUTHOR>
        <QUANTITY>298</QUANTITY>
        <PRICE>5.30</PRICE>
   </BOOK>
   <BOOK>
        <TITLE>The Talisman</TITLE>
        <AUTHOR>Stephen King</AUTHOR>
        <COAUTHOR>Peter Straub</COAUTHOR>
	<COAUTHOR>Stephen King</COAUTHOR>
        <QUANTITY>1008</QUANTITY>
        <PRICE>8:40</PRICE>
   </BOOK>
   <BOOK>
        <TITLE>First to Die</TITLE>
        <AUTHOR>James Patterson</AUTHOR>
        <QUANTITY>198</QUANTITY>
        <PRICE>6:10</PRICE>
   </BOOK>
   <BOOK>
        <TITLE>Christine</TITLE>
	<SUBTITLE>Stephen King Collection</SUBTITLE>
        <AUTHOR>Stephen King</AUTHOR>
        <QUANTITY>502</QUANTITY>
        <PRICE>5:00</PRICE>
   </BOOK>
</INVENTORY>
