<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE INVENTORY [
    <!ELEMENT INVENTORY (BOOK+)>
             <!ATTLIST BOOK Class (Fiction | Nonfiction | Biorgraphy) #IMPLIED>
        <!ELEMENT BOOK (TITLE, SUBTITLE?, AUTHOR,  COAUTHOR*, QUANTITY, PRICE)>
             <!ELEMENT TITLE (#PCDATA)>
             <!ELEMENT SUBTITLE (#PCDATA)>
             <!ELEMENT AUTHOR (#PCDATA)>
             <!ELEMENT QUANTITY (#PCDATA)>
             <!ELEMENT COAUTHOR (#PCDATA)>
             <!ELEMENT PRICE (#PCDATA)>           
         ]>
         

<INVENTORY>
    
    <BOOK>
        <TITLE></TITLE>
        <AUTHOR></AUTHOR>
        <QUANTITY></QUANTITY>
        <PRICE></PRICE>
    </BOOK>
    
    
</INVENTORY>