=== rpmullig/DATABASES_AND_RELATED/XML/Projects_done_at_IU/Projects/Grammies_XML/team6_project1.xsd
<?xml version="1.0" encoding="utf-8"?>

<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="MUSIC">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" name="ARTIST">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="ARTISTNAME" type="xs:string"/> 
              <xs:element name="ARTISTTYPE" type="xs:string"/> 
              <xs:element name="ARTISTCOUNTRY" type="xs:string"/>
              <xs:element name="GROUPNAMES" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
              <xs:element name="CAREERSTART" minOccurs="0" >
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:pattern value="([0-9]{4})(s)?"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="CAREEREND" minOccurs="0">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:pattern value="([0-9]{4})(s)?"/>
                    <xs:pattern value="Present"/>
                    <xs:pattern value=""/>
                    <xs:pattern value="N/A"></xs:pattern>
                  </xs:restriction>  
                </xs:simpleType>
              </xs:element>               
              <xs:element name="GENRE" type="xs:string" />
              <xs:element name="ALBUM" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="TEAMRANKING" minOccurs="0">
                      <xs:simpleType>
                        <xs:restriction base="xs:positiveInteger">
                          <xs:minInclusive value="1"></xs:minInclusive>
                          <xs:maxInclusive value="15"></xs:maxInclusive>
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
                    <xs:element minOccurs="0" name="RATING" >
                      <xs:simpleType>
                        <xs:restriction base="xs:integer">
                          <xs:maxInclusive value="10"/>
                          <xs:minInclusive value="1" />
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
                    <xs:element name="COMMENT">
                      <xs:simpleType>
                        <xs:restriction base="xs:string">
                          <xs:minLength value="10" />
                          <xs:maxLength value="250" />
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
                    <xs:element name="ALBUMNAME"  >
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute name="albumCategory" use="required">
                              <xs:simpleType>
                                <xs:restriction base="xs:string">
                                  <xs:enumeration value="Grammy_Winner"/>
                                  <xs:enumeration value="Grammy_Nominee"/>
                                  <xs:enumeration value="Personal_Favorite"/>
                                </xs:restriction>
                              </xs:simpleType>
                            </xs:attribute>
                            <xs:attribute name="type" type="productType" use="required" >
                            </xs:attribute>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="ALBUMCOVER">
                        <xs:simpleType>
                        <xs:restriction base="xs:string">
                             <xs:pattern value=".+[.](jpeg|png|jpg)"/>
                          
                        </xs:restriction>
                        </xs:simpleType>
                    </xs:element>
                    <xs:element name="IMAGESOURCE" type="xs:string" />
                    <xs:element name="PRODUCERS" minOccurs="0" maxOccurs="unbounded" type="xs:string" />
                    <xs:element name="MIXERS" minOccurs="0"  maxOccurs="unbounded" type="xs:string" />
                    <xs:element name="MASTERENGINEERS" minOccurs="0"  maxOccurs="unbounded" type="xs:string" />
                    <xs:element name="LABEL" minOccurs="0" type="xs:string" />
                    <xs:element name="RELEASEINFORMATION">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element maxOccurs="unbounded" name="RELEASEDATA">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="RELEASEDATE" minOccurs="0">
                                  <xs:simpleType>
                                    <xs:restriction base="xs:string" >
                                      <xs:pattern value="([0-9])*([/]|[-])?([0-9]*)([/]|[-])?([0-9]*)"/>
                                      <!-- One XML file had the date data wrong so we made it accepting to all data in the file -->
                                    </xs:restriction>
                                  </xs:simpleType>
                                </xs:element>
                                <xs:element minOccurs="0" name="RECORDLABEL" type="xs:string" />
                                <xs:element minOccurs="0" name="RECORDLABELCATALOGNUMBER" type="xs:string" />
                                <xs:element minOccurs="0" name="BARCODENUMBER" type="xs:string" />
                                <xs:element minOccurs="0" name="COUNTRY" type="xs:string" />
                                <xs:element minOccurs="0" name="FORMAT" type="xs:string" />
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="TRACKLIST">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element maxOccurs="unbounded" name="SONG">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="SONGNAME" type="xs:string"/>
                                <xs:element name="SONGLENGTH"      >
                                <xs:simpleType>
                                  <xs:restriction base="xs:string">
                                    <xs:pattern value="([0-9]*)(:)[0-9]{2}" />
                                  </xs:restriction>
                                </xs:simpleType>
                                </xs:element>
                                <xs:element name="COMPOSERS" type="xs:string" />
                                <xs:element name="SONGNUMBER" type="xs:integer"/>
                              </xs:sequence>
                              <xs:attribute name="sku" use="required" >
                                <xs:simpleType>
                                  <xs:restriction base="xs:ID">
                                    <xs:pattern value=".+[-](K315FL15)[A-Z]([0-9]{3})" />
                                    <xs:pattern value=".+[-](K315FL)[A-Z]([0-9]{3})" />
                                    <!-- One XML file was missing the 15 in the data so we added it to the pattern value accepted-->
                                  </xs:restriction>
                                </xs:simpleType>
                              </xs:attribute>
                              <xs:attribute name="albumref" use="required">
                                <xs:simpleType>
                                  <xs:restriction base="xs:IDREF">
                                    <xs:pattern value=".+[-](K315FL15)([A-Z])"></xs:pattern>
                                  </xs:restriction>
                                </xs:simpleType>
                              </xs:attribute>
                              <xs:attribute name="type" type="xs:string" use="required" />
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="sku" use="required" >
                    <xs:simpleType>
                    <xs:restriction base="xs:ID">
                      <xs:pattern value=".+[-](K315FL15)([A-Z])" />
                    </xs:restriction>
                  </xs:simpleType>
                 </xs:attribute>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>




  <xs:simpleType name="productType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="song"/>
      <xs:enumeration value="album"/>
    </xs:restriction>
  </xs:simpleType>


</xs:schema>

=== rpmullig/DATABASES_AND_RELATED/XML/Projects_done_at_IU/Projects/Grammies_XML/team6_project1_2trans.xml
<?xml version="1.0" encoding="utf-8"?>
<MUSIC xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="team6_project1.xsd">
   <ARTIST>
      <ARTISTNAME>Beck</ARTISTNAME>
      <ARTISTTYPE>Person</ARTISTTYPE>
      <ARTISTCOUNTRY>US</ARTISTCOUNTRY>
      <GROUPNAMES/>
      <CAREERSTART>1990s</CAREERSTART>
      <CAREEREND>2010s</CAREEREND>
      <GENRE>Pop/Rock, Electronic</GENRE>
      <ALBUM sku="hw26-K315FL15A">
         <RATING>7</RATING>
         <COMMENT>I like the design of the Album</COMMENT>
         <ALBUMNAME albumCategory="Grammy_Winner" type="album">Morning Phase</ALBUMNAME>
         <ALBUMCOVER>Morning_Phase.jpg</ALBUMCOVER>
         <IMAGESOURCE>https://en.wikipedia.org/wiki/Morning_Phase</IMAGESOURCE>
         <PRODUCERS>Beck Hansen</PRODUCERS>
         <MIXERS>Tom Elmhirst, David Greenbaum, Cole Marsden Greif-Neill, Florian Lagatta, Robbie Nelson, Darrell Thorp, Cassidy Turbin &amp; Joe Visciano</MIXERS>
         <MASTERENGINEERS>Bob Ludwig</MASTERENGINEERS>
         <LABEL>Capitol Records</LABEL>
         <RELEASEINFORMATION>
            <RELEASEDATA>
               <RELEASEDATE>02/21/2014</RELEASEDATE>
               <RECORDLABEL>Fonograf Records</RECORDLABEL>
               <RECORDLABELCATALOGNUMBER/>
               <BARCODENUMBER>[none]</BARCODENUMBER>
               <COUNTRY/>
               <FORMAT>Digital Media</FORMAT>
            </RELEASEDATA>
            <RELEASEDATA>
               <RELEASEDATE>02/25/2014</RELEASEDATE>
               <RECORDLABEL>Fonograf Records</RECORDLABEL>
               <RECORDLABELCATALOGNUMBER>3764975</RECORDLABELCATALOGNUMBER>
               <BARCODENUMBER>602537649754</BARCODENUMBER>
               <COUNTRY>AU</COUNTRY>
               <FORMAT>CD</FORMAT>
            </RELEASEDATA>
            <RELEASEDATA>
               <RELEASEDATE>02/25/2014</RELEASEDATE>
               <RECORDLABEL>Capitol Records (imprint of Capitol Records, Inc.)</RECORDLABEL>
               <RECORDLABELCATALOGNUMBER>B001983802</RECORDLABELCATALOGNUMBER>
               <BARCODENUMBER>602537649754</BARCODENUMBER>
               <COUNTRY>CA</COUNTRY>
               <FORMAT>CD</FORMAT>
            </RELEASEDATA>
            <RELEASEDATA>
               <RELEASEDATE>02/25/2014</RELEASEDATE>
               <RECORDLABEL>Capitol Records (imprint of Capitol Records, Inc.)</RECORDLABEL>
               <RECORDLABELCATALOGNUMBER>602537649754</RECORDLABELCATALOGNUMBER>
               <BARCODENUMBER>602537649754</BARCODENUMBER>
               <COUNTRY>XE</COUNTRY>
               <FORMAT>CD</FORMAT>
            </RELEASEDATA>
            <RELEASEDATA>
               <RELEASEDATE>02/25/2014</RELEASEDATE>
               <RECORDLABEL>Capitol Records (imprint of Capitol Records, Inc.)</RECORDLABEL>
               <RECORDLABELCATALOGNUMBER>B001983901</RECORDLABELCATALOGNUMBER>
               <BARCODENUMBER>602537649747</BARCODENUMBER>
               <COUNTRY>US</COUNTRY>
               <FORMAT>Vinyl</FORMAT>
            </RELEASEDATA>
            <RELEASEDATA>
               <RELEASEDATE>02/25/2014</RELEASEDATE>
               <RECORDLABEL>Capitol Records (imprint of Capitol Records, Inc.)</RECORDLABEL>
               <RECORDLABELCATALOGNUMBER>B001983802</RECORDLABELCATALOGNUMBER>
               <BARCODENUMBER>602537649754</BARCODENUMBER>
               <COUNTRY>US</COUNTRY>
               <FORMAT>CD</FORMAT>
            </RELEASEDATA>
            <RELEASEDATA>
               <RELEASEDATE>07/06/1905</RELEASEDATE>
               <RECORDLABEL>Capitol Records (imprint of Capitol Records, Inc.)</RECORDLABEL>
               <RECORDLABELCATALOGNUMBER/>
               <BARCODENUMBER>[none]</BARCODENUMBER>
               <COUNTRY>US</COUNTRY>
               <FORMAT>Digital Media</FORMAT>
            </RELEASEDATA>
         </RELEASEINFORMATION>
         <TRACKLIST>
            <SONG sku="hw26-K315FL15A001" albumref="hw26-K315FL15A" type="song">
               <SONGNAME>Cycle</SONGNAME>
               <SONGLENGTH>0:40</SONGLENGTH>
               <COMPOSERS>Beck Hansen</COMPOSERS>
               <SONGNUMBER>1</SONGNUMBER>
            </SONG>
            <SONG sku="hw26-K315FL15A002" albumref="hw26-K315FL15A" type="song">
               <SONGNAME>Morning</SONGNAME>
               <SONGLENGTH>5:19</SONGLENGTH>
               <COMPOSERS>Beck Hansen</COMPOSERS>
               <SONGNUMBER>2</SONGNUMBER>
            </SONG>
            <SONG sku="hw26-K315FL15A003" albumref="hw26-K315FL15A" type="song">
               <SONGNAME>Heart Is a Drum</SONGNAME>
               <SONGLENGTH>4:31</SONGLENGTH>
               <COMPOSERS>Beck Hansen</COMPOSERS>
               <SONGNUMBER>3</SONGNUMBER>
            </SONG>
            <SONG sku="hw26-K315FL15A004" albumref="hw26-K315FL15A" type="song">
               <SONGNAME>Say Goodbye</SONGNAME>
               <SONGLENGTH>3:29</SONGLENGTH>
               <COMPOSERS>Beck Hansen</COMPOSERS>
               <SONGNUMBER>4</SONGNUMBER>
            </SONG>
            <SONG sku="hw26-K315FL15A005" albumref="hw26-K315FL15A" type="song">
               <SONGNAME>Blue Moon</SONGNAME>
               <SONGLENGTH>4:02</SONGLENGTH>
               <COMPOSERS>Beck Hansen</COMPOSERS>
               <SONGNUMBER>5</SONGNUMBER>
            </SONG>
            <SONG sku="hw26-K315FL15A006" albumref="hw26-K315FL15A" type="song">
               <SONGNAME>Unforgiven</SONGNAME>
               <SONGLENGTH>4:34</SONGLENGTH>
               <COMPOSERS>Beck Hansen</COMPOSERS>
               <SONGNUMBER>6</SONGNUMBER>
            </SONG>
            <SONG sku="hw26-K315FL15A007" albumref="hw26-K315FL15A" type="song">
               <SONGNAME>Wave</SONGNAME>
               <SONGLENGTH>3:40</SONGLENGTH>
               <COMPOSERS>Beck Hansen</COMPOSERS>
               <SONGNUMBER>7</SONGNUMBER>
            </SONG>
            <SONG sku="hw26-K315FL15A008" albumref="hw26-K315FL15A" type="song">
               <SONGNAME>Don't Let It Go</SONGNAME>
               <SONGLENGTH>3:09</SONGLENGTH>
               <COMPOSERS>Beck Hansen</COMPOSERS>
               <SONGNUMBER>8</SONGNUMBER>
            </SONG>
            <SONG sku="hw26-K315FL15A009" albumref="hw26-K315FL15A" type="song">
               <SONGNAME>Blackbird Chain</SONGNAME>
               <SONGLENGTH>4:26</SONGLENGTH>
               <COMPOSERS>Beck Hansen</COMPOSERS>
               <SONGNUMBER>9</SONGNUMBER>
            </SONG>
            <SONG sku="hw26-K315FL15A010" albumref="hw26-K315FL15A" type="song">
               <SONGNAME>Phase</SONGNAME>
               <SONGLENGTH>1:03</SONGLENGTH>
               <COMPOSERS>Beck Hansen</COMPOSERS>
               <SONGNUMBER>10</SONGNUMBER>
            </SONG>
            <SONG sku="hw26-K315FL15A011" albumref="hw26-K315FL15A" type="song">
               <SONGNAME>Turn Away</SONGNAME>
               <SONGLENGTH>3:05</SONGLENGTH>
               <COMPOSERS>Beck Hansen</COMPOSERS>
               <SONGNUMBER>11</SONGNUMBER>
            </SONG>
            <SONG sku="hw26-K315FL15A012" albumref="hw26-K315FL15A" type="song">
               <SONGNAME>Country Down</SONGNAME>
               <SONGLENGTH>4:00</SONGLENGTH>
               <COMPOSERS>Beck Hansen</COMPOSERS>
               <SONGNUMBER>12</SONGNUMBER>
            </SONG>
            <SONG sku="hw26-K315FL15A013" albumref="hw26-K315FL15A" type="song">
               <SONGNAME>Waking Light</SONGNAME>
               <SONGLENGTH>5:02</SONGLENGTH>
               <COMPOSERS>Beck Hansen</COMPOSERS>
               <SONGNUMBER>13</SONGNUMBER>
            </SONG>
         </TRACKLIST>
      </ALBUM>
   </ARTIST>
   <ARTIST>
      <ARTISTNAME>Beyoncé</ARTISTNAME>
      <ARTISTTYPE>Person</ARTISTTYPE>
      <ARTISTCOUNTRY>US</ARTISTCOUNTRY>
      <GROUPNAMES/>
      <CAREERSTART>1990s</CAREERSTART>
      <CAREEREND>2010s</CAREEREND>
      <GENRE>R&amp;B</GENRE>
      <ALBUM sku="hw26-K315FL15B">
         <RATING>8</RATING>
         <COMMENT>Powerful singer</COMMENT>
         <ALBUMNAME albumCategory="Grammy_Nominee" type="album">Beyoncé</ALBUMNAME>
         <ALBUMCOVER>Beyoncé.jpg</ALBUMCOVER>
         <IMAGESOURCE>https://en.wikipedia.org/wiki/Beyonc%C3%A9_(album)</IMAGESOURCE>
         <PRODUCERS>Ammo, Boots, James Fauntleroy, Noel "Detail" Fisher, Jerome Harmon, Hit-Boy, Beyoncé Knowles, Terius "The Dream" Nash, Caroline Polachek, Rey Reel, Noah "40" Shebib, Ryan Tedder, Timbaland, Justin Timberlake, Key Wane, Pharrell Williams &amp; Patrick Wimberly</PRODUCERS>
         <MIXERS>Boots, Noel Cadastre, Noel "Gadget" Campbell, Rob Cohen, Andrew Coleman, Chris Godbey, Justin Hergett, James Krausse, Mike Larson, Jonathan Lee, Tony Maserati, Ann Mincieli, Caroline Polachek, Andrew Scheps, Bart Schoudel, Noah "40" Shebib, Ryan Tedder, Stuart White &amp; Jordan "DJ Swivel" Young</MIXERS>
         <MASTERENGINEERS>Tom Coyne, James Krausse &amp; Aya Merrill</MASTERENGINEERS>
         <LABEL>Columbia Records</LABEL>
         <RELEASEINFORMATION>
            <RELEASEDATA>
               <RELEASEDATE>12/13/2013</RELEASEDATE>
               <RECORDLABEL>Columbia (imprint owned by CBS between 1938–1990 within US/CA/MX; owned worldwide by Sony Music Entertainment since 1991 except in JP)</RECORDLABEL>
               <RECORDLABELCATALOGNUMBER/>
               <BARCODENUMBER/>
               <COUNTRY>XW</COUNTRY>
               <FORMAT>Digital Media</FORMAT>
            </RELEASEDATA>
            <RELEASEDATA>
               <RELEASEDATE>12/20/2013</RELEASEDATE>
               <RECORDLABEL>Columbia (imprint owned by CBS between 1938–1990 within US/CA/MX; owned worldwide by Sony Music Entertainment since 1991 except in JP), Parkwood Entertainment</RECORDLABEL>
               <RECORDLABELCATALOGNUMBER>88843032512</RECORDLABELCATALOGNUMBER>
               <BARCODENUMBER>888430325128</BARCODENUMBER>
               <COUNTRY>XE</COUNTRY>
               <FORMAT>CD + DVD-Video</FORMAT>
            </RELEASEDATA>
            <RELEASEDATA>
